### ISSUE TITLE
About multi-thread train

### ISSUE THREAD

**Issue by AsherChan** [HKUST-KnowComp/JWE#3]
hello,I am confuse about the speed of multi-thread training,for I train with 8 threads as default, but the took tens of times compare with trainning word2vec with gensim.  I also use command $top to watch the usage of CPU, it's higher than I train with gensim

**Comment by AsherChan** [comment]
`Alpha: 0.024633  Progress: 1.47%  Words/thread/sec: 11.20k  
Alpha: 0.024632  Progress: 1.47%  Words/thread/sec: 11.20k  
Alpha: 0.016852  Progress: 32.59%  Words/thread/sec: 10.88k  
Alpha: 0.013359  Progress: 46.56%  Words/thread/sec: 10.87k  
Alpha: 0.007946  Progress: 68.22%  Words/thread/sec: 10.89k  
Alpha: 0.001789  Progress: 92.84%  Words/thread/sec: 10.91k  
`
this is the speed show in my command terminal

**Comment by jinxing94** [comment]
Admittedly, the running time of JWE is longer than that of word2vec model.
This is because JWE model incorporates the characters and components and has additional computation to update the embeddings of characters and components during training.
Other variants of word2vec such as CWE and MGE also have larger time complexity compared with word2vec.

**Comment by jinxing94** [comment]
The implementation is based on the google word2vec c source code. The multi-thread training uses data parallelism with asynchronous sgd. It is approximately linear speed up w.r.t cpu-cores.
